text = 'Welcome to Python course.\nPython is amazing!'

print('Capitalize:\n', text.capitalize())
print('*' * 10)
print('Title:\n', text.title())
print('*' * 10)
print('Count \'Python\' words:', text.count('Python'))
print('*' * 10)
print('Starts with word \'Welcome\':', text.startswith('Welcome'))
print('Starts with word \'course\':', text.startswith('course'))
print('*' * 10)
print('Ends with word \'amazing!\':', text.endswith('amazing!'))
print('Ends with word \'amazing\':', text.endswith('amazing'))
print('*' * 10)
print('Find start index for word \'Python\':', text.find('Python'))
print('*' * 10)
print('Is All Alphanumerics?', text.isalnum())
print('*' * 10)
print('Digit?', text.isdigit())
print('*' * 10)
print('Lower?', text.islower())
print('Upper?', text.isupper())
print('*' * 10)
print(' '.join(['Python', 'Is', 'Cool']))
print('#'.join(['Python', 'Is', 'Cool']))
print('*' * 10)
print('#good#time#mood'.replace('#', ' '))
print('*' * 10)
print('Strip:', '   python    '.strip())
print('Right strip:', '   python    '.rstrip())
print('Left strip:', '   python    '.lstrip())
print('*' * 10)
print('1,2,3,4,5'.split(','))
print('Python Java PHP SQL'.split())
print('*' * 10)
print('12'.zfill(5))
